# Generated by Django 2.1.4 on 2019-05-17 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('panel', '0015_auto_20190419_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='GHResultKeywordMeter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_id', models.IntegerField()),
                ('ghUrl', models.CharField(max_length=1000)),
                ('repo_name', models.CharField(max_length=300)),
                ('is_vulnerable_our_algorithm', models.BooleanField(default=False, verbose_name='Own Vulnerable ?')),
                ('is_vulnerable_random_algorithm', models.BooleanField(default=False, verbose_name='Random Vulnerable ?')),
                ('is_error', models.BooleanField(default=False, verbose_name='ERROR ?')),
                ('report', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Code')),
            ],
            options={
                'verbose_name_plural': 'Github Results - Meter',
            },
        ),
        migrations.AlterUniqueTogether(
            name='ghresultkeywordmeter',
            unique_together={('answer_id', 'ghUrl', 'code')},
        ),
    ]
