# Generated by Django 2.1.4 on 2018-12-21 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Filename')),
                ('group_id', models.IntegerField(verbose_name='Group ID')),
                ('snipped_code', models.TextField(verbose_name='Snipped Code')),
                ('reviewed', models.BooleanField(default=False, verbose_name='Is Reviewed ?')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='sourl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Code')),
            ],
        ),
    ]
