# Generated by Django 2.1.4 on 2018-12-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='is_vulnerable',
            field=models.BooleanField(default=False, verbose_name='Is Vulnerable ?'),
        ),
    ]
