# Generated by Django 2.1.4 on 2018-12-31 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_code_is_vulnerable'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='answer_id',
            field=models.IntegerField(default=0, verbose_name='Answer ID'),
        ),
    ]
