# Generated by Django 2.1.4 on 2018-12-31 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_code_answer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code_Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='code',
            name='answer_id',
        ),
        migrations.AddField(
            model_name='code_answer',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Code'),
        ),
    ]
