# Generated by Django 2.1.4 on 2018-12-31 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_code_answer_qestion_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code_answer',
            old_name='qestion_id',
            new_name='question_id',
        ),
    ]
