# Generated by Django 2.1.4 on 2019-01-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_auto_20190102_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='code_answer',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Done ?'),
        ),
    ]
