# Generated by Django 2.1.4 on 2019-01-15 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_code_answer_is_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='GHResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_id', models.IntegerField()),
                ('ghUrl', models.CharField(max_length=1000)),
                ('is_vulnerable', models.BooleanField(default=False, verbose_name='Vulnerable ?')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Checked ?')),
                ('is_error', models.BooleanField(default=False, verbose_name='ERROR ?')),
                ('report', models.CharField(blank=True, default='', max_length=1000, null=True)),
            ],
        ),
    ]
