# Generated by Django 2.1.4 on 2019-01-15 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0009_ghresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ghresult',
            options={'verbose_name_plural': 'Github Results'},
        ),
        migrations.AddField(
            model_name='ghresult',
            name='code',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='panel.Code'),
        ),
    ]
