# Generated by Django 2.1.4 on 2019-01-15 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0010_auto_20190115_0248'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ghresult',
            unique_together={('answer_id', 'ghUrl')},
        ),
    ]
