# Generated by Django 2.1.4 on 2019-01-15 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0011_auto_20190115_0330'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ghresult',
            unique_together={('answer_id', 'ghUrl', 'code')},
        ),
    ]
