# Generated by Django 2.1.4 on 2019-01-24 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0012_auto_20190115_0456'),
    ]

    operations = [
        migrations.CreateModel(
            name='GHResult_LastVersions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_id', models.IntegerField()),
                ('ghUrl', models.CharField(max_length=1000)),
                ('is_vulnerable', models.BooleanField(default=False, verbose_name='Vulnerable ?')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Checked ?')),
                ('is_error', models.BooleanField(default=False, verbose_name='ERROR ?')),
                ('report', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('code', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='panel.Code')),
            ],
            options={
                'verbose_name_plural': 'Github Results - Last Versions',
            },
        ),
        migrations.AlterUniqueTogether(
            name='ghresult_lastversions',
            unique_together={('answer_id', 'ghUrl', 'code')},
        ),
    ]
