# Generated by Django 2.1.4 on 2019-03-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0013_auto_20190124_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghresult_lastversions',
            name='repo_name',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
